mob-heads:
  'CHICKEN':
    settings:
      min-value: 1
      max-value: 3
      chance-to-drop: 90
      head: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWQxN2U0OGM5MjUzZTY3NDczM2NlYjdiYzNkYTdmNTIxNTFlNTI4OWQwMjEyYzhmMmRkNzFlNDE2ZTRlZTY1In19fQ=='
      message-on-drop:
        to-killer: '&fYou killed a Chicken and got a head worth %value%'
    item:
      name: '&b&lChicken Head &r&7&o(COMMON)'
      lore:
        - '&f '
        - '&fYou received a Chicken Head'
        - '&ffor killing a Chicken! This head'
        - '&fhas a value of $%value%! Right'
        - '&fclick to redeem'
    actions:
      - '[CONSOLECOMMAND] eco give %player_name% %value%'

player-heads:
  enabled: true
  settings:
    money-percentage: 25
    chance-to-drop: 10
    message-on-drop:
      to-killer: '&fYou killed %victim% and have 25% of their balance in this head (value: %value%) - Click to redeem'
      to-victim: '&f%killer% killed you and has 25% of your balance in a head (value: %value%)'
  item:
    name: '&b&l%victim%''s Head &r&7&o(RARE)'
    lore:
      - '&f '
      - '&fYou received %victim%'' Head'
      - '&fThis holds 25% of their balance and'
      - '&fhas a value of $%value%! Right'
      - '&fclick to redeem'
      - '&fKiller: %killer%'
  actions:
    - '[CONSOLECOMMAND] eco give %player_name% %value%'